hzm/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from . import apis,apis_freeboard
from django.conf.urls.static import static
from django.conf import settings

app_name ='hzm'

urlpatterns = [
	path('',views.main_page, name='main_page'),
	path('error',views.error_page,name='error_page'),
	path('schedule/', views.schedule, name='schedule'),
	path('signin/',views.signin_page,name='signin_page'),
	path('signup/',views.signup,name='signup'),
	path('match/',views.match,name='match'),
	path('match/info/<int:match_pk>/',views.match_info,name='match_info'),
	path('match_before/',views.match_before,name='match_before'),
	path('match_before/info/<int:match_pk>/',views.match_before_info,name='match_before_info'),
	path('mypage/',views.mypage, name='mypage'),
	path('personal_record',views.personal_record,name='personal_record'),
	path('club/<int:club_pk>/',views.club,name='club'),
	path('match_form/',views.match_form,name='match_form'),
	path('api/signin',apis.sign_in,name='ajax_signin'),
	path('api/signup',apis.sign_up,name='ajax_signup'),
	path('api/logout',apis.logout,name='ajax_logout'),
	path('api/add_fmatch',apis.add_fmatch,name='ajax_add_fmatch'),
	path('api/add_schedule',apis.add_schedule,name='ajax_add_schedule'),
	path('api/get_my_schedules',apis.get_my_schedules,name='ajax_get_my_schedules'),
	path('api/get_all_schedules',apis.get_all_schedules,name='ajax_get_all_schedules'),
	path('api/create_my_schedule_table',apis.create_my_schedule_table,name='ajax_create_my_schedule_table'),
	path('api/id_check',apis.id_check, name='ajax_id_check'),
	path('api/id_check_btn',apis.id_check_btn, name='ajax_id_check_btn'),
	path('api/delete_my_schedule',apis.delete_my_schedule, name='ajax_delete_my_schedule'),
	path('api/edit_my_schedule',apis.edit_my_schedule, name='ajax_edit_my_schedule'),
	path('api/crate_match_list',apis.create_match_list, name='ajax_create_match_list'),
	path('api/edit_mypage_info',apis.edit_mypage_info, name='ajax_edit_mypage_info'),
	path('api/delete_before_match_info/<int:match_pk>/',apis.delete_before_match_info, name='delete_before_match_info'),
	path('api/delete_match_info/<int:match_pk>/',apis.delete_match_info, name='delete_match_info'),
	path('api/accept_match_info/<int:match_pk>/',apis.accept_match_info, name='accept_match_info'),
	path('api/check_post_passwd',apis.check_post_passwd,name='ajax_check_post_passwd'),
	path('api/save_match_info',apis.save_match_info,name='ajax_save_match_info'),
	path('api/save_admin_match_info',apis.save_admin_match_info,name='ajax_admin_save_match_info'),
	path('api/get_redteam_player',apis.get_redteam_player,name='ajax_get_redteam_player'),
	path('api/get_redteam_subplayer',apis.get_redteam_subplayer,name='ajax_get_redteam_subplayer'),
	path('api/save_redteam_player',apis.save_redteam_player,name='ajax_save_redteam_player'),
	path('api/save_matchresult',apis.save_matchresult,name='ajax_save_matchresult'),
	path('api/add_map_record',apis.add_map_record,name='ajax_add_map_record'),
	path('api/get_records',apis.get_records,name='ajax_get_records'),
	path('api/get_record_rank',apis.get_record_rank,name='ajax_get_record_rank'),
	path('api/get_player_before_auth',apis.get_player_before_auth,name='ajax_get_player_before_auth'),
	path('api/accept_player',apis.accept_player,name='ajax_accept_player'),
	path('api/reject_player',apis.reject_player,name='ajax_reject_player'),
	path('api/match_filter',views.match_filter,name='ajax_match_filter'),
	path('club/<int:club_pk>/admin/',views.club_admin,name='club_admin'),
	path('api/add_admin_record',apis.add_admin_record,name='ajax_add_admin_record'),
	path('api/add_admin_record',apis.add_admin_record,name='ajax_add_admin_record'),
	path('freeboard/',views.freeboard,name='freeboard'),
	path('freeboard/write',views.freeboard_write,name='freeboard_write'),
	path('freeboard/<int:post_pk>/',views.freeboard_info,name='freeboard_info'),
	path('api/save_club_description',apis.save_club_description,name='ajax_save_club_description'),
	path('api/add_freeboard_comment',apis.add_freeboard_comment ,name='ajax_add_freeboard_comment'),
	path('api/add_freeboard_writing',apis_freeboard.add_freeboard_writing ,name='ajax_add_freeboard_writing'),
	path('api/delete_admin_record',apis.delete_admin_record ,name='ajax_delete_admin_record'),
	path('api/edit_admin_record',apis.edit_admin_record ,name='ajax_edit_admin_record'),
	path('api/delete_freeboardcomment',apis_freeboard.delete_freeboardcomment ,name='ajax_delete_freeboardcomment'),
	path('freeboard/edit/<int:freeboard_pk>',views.freeboard_edit ,name='freeboard_edit'),
	path('api/edit_freeboard_writing',apis_freeboard.edit_freeboard_writing ,name='ajax_edit_freeboard_writing'),
	path('api/delete_freeboard_writing',apis_freeboard.delete_freeboard_writing ,name='ajax_delete_freeboard_writing'),
	path('api/get_club_member',apis.get_club_member ,name='ajax_get_club_member'),
	
]

hzm_site/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hzm.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hzm/views.py
from __future__ import unicode_literals
from django.shortcuts import render,redirect
from django.http import HttpResponse, JsonResponse,HttpResponseRedirect
from django.urls import reverse
from hzm.models import *
from django.views.decorators.csrf import csrf_exempt
from django.forms.models import model_to_dict
import json
import datetime
import time
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.db.models import Q
from hzm.logs import *
import logging
from django.db.models import Count,Max,Min
from pandas import Series

#from datetime import datetime
# Create your views here.
SIZE_FREEBOARD_DESCRIPTION=1000
SIZE_POST_COMMENT=200

log_dir = create_dir()

def record_win_lose(player_id,club_id) :
	matches=Match.objects.filter(Q(red_club_id=club_id) & Q(red_player_id__contains=[player_id]))
	player=Player.objects.get(pk=player_id)
	player.win=0
	player.lose=0
	for match in matches :
		if match.red_win > match.blue_win :
			player.win += 1
		else :
			player.lose += 1
	player.save()
	return False


def club_member_match_stat(club_id) :
	players=Player.objects.filter( Q(club_id=club_id) & Q(accept=True))

	for player in players :
		record_win_lose(player.pk,club_id)
	return False

def main_page(request) :
	pk=request.session.get('pk')
	club_id=request.session.get('club_id')
	
	freeboard=Freeboard.objects.all().order_by('-date')
	freeboard_paginator = Paginator(freeboard, 5)
	freeboards = freeboard_paginator.get_page(1)

	match=Match.objects.filter(accept=True).order_by('-match_date')
	match_paginator = Paginator(match, 5)
	matches = match_paginator.get_page(1)

	if pk is not None :
		player=Player.objects.get(pk=pk)
		log_start(request,log_dir+'/'+str(player.pk)+'.log',player.player_name+" in main page")
		club=Club.objects.get(pk=player.club_id)
		return render(request,'hzm/main_page.html',{'pk':pk,'player':player,'club':club,'freeboards':freeboards,'matches':matches})
	else :
		log_start(request,log_dir+'/today.log','main page')
		return render(request,'hzm/main_page.html',{'freeboards':freeboards, 'matches':matches})

def mypage(request) :
	pk=request.session.get('pk')

	if pk is None :
		request.session.clear()
		return redirect('/')
		
	try : 
		player=Player.objects.get(pk=pk)
		club=Club.objects.get(pk=player.club_id)
		log_start(request,log_dir+'/'+str(player.pk)+'.log',player.player_name+" in mypage")
	except Exception as e :
		print(e)
		return redirect('/')
	return render(request,'hzm/mypage.html',{'pk':pk ,'player':player,'club':club})

def schedule(request) :
	pk=request.session.get('pk')
	player_name=request.session.get('player_name')
	try :
		if pk is not None :
			player=Player.objects.get(pk=pk)
			club=Club.objects.get(pk=player.club_id)
			return render(request, 'hzm/schedule.html', {'pk':pk, 'player':player, 'club':club})
		else :
			return redirect('/')
	except Exception as e :
		return redirect('/')



def signin_page(request) :
	return render(request,'hzm/signin_page.html')

def signup(request) :
	pk = request.session.get('pk')

	if pk is not None :
		return redirect('hzm:main_page')
		
	clubs=Club.objects.all()
	return render(request,'hzm/signup.html',{'clubs':clubs})

def match(request) :
	pk=request.session.get('pk')
	club_id = request.session.get('club_id')
	matches = Match.objects.all().filter(Q(accept=True)).order_by('-match_date')
	count = matches.count()
	paginator = Paginator(matches, 10)
	pages = request.GET.get('page',1)
	
	clubs=Club.objects.all().order_by('club_name')

	now = time.strftime('%Y-%m-%d %I:%M',time.localtime())
	for match in matches :
		match_date_start = match.match_date+' '+match.match_time_start
		match_date_end = match.match_date+' '+match.match_time_end

		if match_date_start > now :
			match.state="경기준비"
		elif match_date_end < now :
			match.state="경기종료"
		else :
			match.state="진행중"

		match.save()

	try :
		matches = paginator.get_page(pages)
	except PageNotAnInteger :
		matches = paginator.page(1)
	except EmptyPage :
		matches = paginator.page(paginator.num_pages)
		return HttpResponse("end")

	if pk :
		player=Player.objects.get(pk=pk)
		club=Club.objects.get(pk=player.club_id)
		return render(request, 'hzm/match.html',{'matches' : matches, 'match_count':count ,'pk':pk ,'clubs':clubs,'club':club})
	else :
		return render(request, 'hzm/match.html',{'matches' : matches, 'match_count':count})


def match_info(request,match_pk) :
	match_pk=match_pk
	pk=request.session.get('pk')
	player_name=request.session.get('player_name') 
	club_id=request.session.get('club_id')


	
	try :
		match = Match.objects.get(pk=match_pk)
		if match.accept == False :
			return render(request, 'hzm/error.html')
		if pk is not None :
			player=Player.objects.get(pk=pk)
			club=Club.objects.get(pk=club_id)
			return render(request, 'hzm/match_info.html', {'match':match, 'pk':pk, 'player':player,'club':club})
		else :
			return render(request, 'hzm/match_info.html', {'match':match, 'pk':pk})
	except Exception as e :
		return render(request, 'hzm/error.html')

def match_before_info(request,match_pk) :
	
	try :
		match=Match.objects.get(pk=match_pk)
		
		if match.accept == True :
			raise("잘못된접근")

		pk=request.session.get('pk')
		player_name=request.session.get('player_name') 
		club_id=request.session.get('club_id')
		club=Club.objects.get(pk=club_id)
		try :			
			if match.red_club_id != club.pk :
				return render(request,'hzm:main_page.html')
		except Exception as e:
			print(e)
			return render('hzm:error')


		if pk is None :
			return redirect("/")
		elif player_name is None :
			return redirect("/")

		match = Match.objects.get(pk=match_pk)

		if match.accept == True :
			raise('error')

		return render(request, 'hzm/match_before_info.html', {'match':match, 'pk':pk, 'player_name':player_name,'club':club})
	except Exception as e :
		print(e)
		return HttpResponseRedirect(reverse('hzm:error_page'))

def match_before(request) :

	pk=request.session.get('pk')
	player_name=request.session.get('player_name') 
	club_id=request.session.get('club_id')

	if pk is None :
		return redirect('/')

	try :
		club=Club.objects.get(pk=club_id)
		player=Player.objects.get(pk=pk)
	except Exception as e :
		return redirect('/')

	matches = Match.objects.all().filter(Q(accept=False) & Q(red_club_id=club_id)).order_by('-pk')
	count = matches.count()
	paginator = Paginator(matches, 2)
	pages = request.GET.get('page',1)

	try :
		matches = paginator.get_page(pages)
	except PageNotAnInteger :
		matches = paginator.page(1)
	except EmptyPage :
		matches = paginator.page(paginator.num_pages)
		return HttpResponse("end")

	return render(request, 'hzm/match_before.html',{'matches' : matches, 'count':count, 'pk':pk, 'player_name':player_name,'club':club})

def delete_result(request) :
	return render(request,'hzm/test.html')

def error_page(request) :
	return render(request, 'hzm/error.html')

def personal_record(request) :
	try :
		player_name=request.session.get('player_name')
		pk=request.session.get('pk')
		if pk is None :
			raise Exception("pk is none")
		
		club_id=request.session.get('club_id')
		maps=Map.objects.all().order_by('map_name')	
		records=Record.objects.filter(player_id=pk).order_by('map_name')
		player=Player.objects.get(pk=pk)
		club=Club.objects.get(pk=club_id)
		record_win_lose(pk,club_id)
		matches=Match.objects.filter(Q(red_club_id=club_id) & Q(red_player_id__contains=[pk])).order_by('-match_date')

		if matches.exists() :
			print("ee")
			return render(request, 'hzm/personal_record.html',{'records':records,'maps':maps,'player':player ,'pk':pk,'club':club,'matches':matches})
		else :
			return render(request, 'hzm/personal_record.html',{'records':records,'maps':maps,'player':player ,'pk':pk,'club':club})


	except Exception as e :
		print(e)
		return redirect("/")


def club(request,club_pk) :
	pk=request.session.get('pk')
	club_id=request.session.get('club_id')

	if pk is None :
		return redirect('/')
	try :
		club_member_match_stat(club_id)
		player=Player.objects.get(pk=pk)
		club=Club.objects.get(pk=club_id)
		club_member=Player.objects.filter(Q(club_id=club_id) & Q(accept=True)).count
		return render(request, 'hzm/club.html',{'pk':pk,'player':player,'club':club ,'club_member':club_member})
	except Exception as e :
		print(e)
		return redirect('/')

def match_form(request) :
	pk = request.session.get('pk')
	club_id = request.session.get('club_id')
	clubs=Club.objects.all()

	if pk is not None :
		club=Club.objects.get(pk=club_id)
		return render(request,'hzm/match_form.html',{'pk':pk,'club':club,'clubs':clubs})	
	return render(request,'hzm/match_form.html',{'clubs':clubs})


def match_filter(request) :

	pk=request.session.get('pk')
	club_id = request.session.get('club_id')
	condition=request.GET.get('filter')
	print(condition)
	if condition != "전체" :
		posts = Post_list.objects.all().filter(Q(accept=True) & Q(club_id=condition)).order_by('-pk')
	else :
		posts = Post_list.objects.all().filter(Q(accept=True)).order_by('-pk')

	count = posts.count()
	paginator = Paginator(posts, 10)
	pages = request.GET.get('page',1)

	
	clubs=Club.objects.all().order_by('-pk')

	now = time.strftime('%Y-%m-%d %I:%M',time.localtime())
	for post in posts :
		match_date_start = post.match_date+' '+post.match_time_start
		match_date_end = post.match_date+' '+post.match_time_end
		print(now)
		print(match_date_end)
		if match_date_start > now :
			post.state="경기준비"
		elif match_date_end < now :
			post.state="경기종료"
		else :
			post.state="진행중"
		print(post.state)
		post.save()

	try :
		posts = paginator.get_page(pages)
	except PageNotAnInteger :
		posts = paginator.page(1)
	except EmptyPage :
		posts = paginator.page(paginator.num_pages)
		return HttpResponse("end")

	if pk :
		player=Player.objects.get(pk=pk)
		club=Club.objects.get(pk=player.club_id)
		return render(request, 'hzm/match.html',{'posts' : posts, 'post_count':count ,'pk':pk ,'clubs':clubs,'club':club})
	else :
		return render(request, 'hzm/match.html',{'posts' : posts, 'post_count':count})

hzm/templates/hzm/freeboard_edit.html
<!DOCTYPE html>
<html>
<head>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-YPRPE75FJG"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-YPRPE75FJG');
</script>
	<meta charset="uft-8">
	<meta name="viewprot" content="width=device-width, inital-scale=1, shrinkt-to-fit=no, user-scalable=no">
	<link rel="shortcut icon" type="image/x-icon" href="/static/imgs/icon/favicon.png">

	<!--부트스트랩-->
	 <script src="/static/js/jquery-3.5.1.min.js"></script>
	 <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

	 <!--커스텀-->
	 <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css">
	 <link rel="stylesheet" type="text/css" href="/static/css/custom_swal.css">
	 <link rel="stylesheet" type="text/css" href="/static/css/bt_tab_bar.css?4">
	 <link rel="stylesheet" type="text/css" href="/static/css/top_nav_bar.css?4">
	 <link rel="stylesheet" type="text/css" href="/static/css/freeboard_form.css?1">


	 <!--폰트 어썸-->
	 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">

	 <!--알림창-->
	 <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>


	<title>학지매-글쓰기</title>
</head>
<body style="height:100%;">
	<!--navbar 시작-->
	<nav id="navbar_top" class="navbar navbar-expand-lg navbar-light bg-light">
		{% if pk %}
		<a class="navbar-brand" id="navbar_club_name" href="{% url 'hzm:main_page' %}">{{club.club_name}}</a>
		{% else %}
		<a class="navbar-brand" id="navbar_club_name" href="{% url 'hzm:main_page' %}">학지매</a>
		{% endif %}
		 	 	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
		    		<span class="navbar-toggler-icon"></span>
		  		</button>
		 	 	<div class="collapse navbar-collapse" id="navbarNav">
				    <ul class="navbar-nav">
				      <li class="nav-item dropdown">
				      	<a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">친선 경기</a>
				      	<div class="dropdown-menu">
				      		 <a class="nav-link" href="{% url 'hzm:match_form' %}">&nbsp;경기 신청 <span class="sr-only">(current)</span></a>
				      		{% if pk %}
				      		<a class="nav-link" href="{% url 'hzm:match_before' %}">&nbsp;경기 신청 현황</a>
				      		{% endif %}
				      		<a class="nav-link" href="{% url 'hzm:match' %}">&nbsp;경기 결과</a>
				      	</div>
                      </li>
                      <li class="nav-item">
				        <a class="nav-link" href="{% url 'hzm:freeboard' %}">자유게시판</a>
				      </li>
				      {% if pk %}
				      <li class="nav-item">
				        <a class="nav-link" href="{% url 'hzm:schedule' %}">일정관리</a>
				      </li>
				      <li class="nav-item">
				        <a class="nav-link" id="logout_btn">로그아웃</a>
				      </li>
				      {% else %}
				       <li class="nav-item">
				        <a class="nav-link" id="signin_btn" data-toggle="modal" data-target="#login">로그인</a>
				      </li>
				      <li class="nav-item">
				        <a class="nav-link" id="signup_btn" data-toggle="modal" data-target="#login">가입하기</a>
				      </li>
				      {% endif %}
			</ul>
		</div>
	</nav>
		<!--navbar 끝-->

		<!--middle container-->
		<div id="middle-container" class="container-fluid">
            <div class="WrtingWrap">
                <div class="WriginHeader" >
                    <div class="wrting-title">
                        <div style="display:inline-block;"><h2>자유게시판 글 수정</h2></div>
                        <div class="wrting-tool" style="float:right; display:inline-block;">
                            <button id="write_edit_btn" class="btn btn-secondary bg-dark">저장</button>
                        </div>                       
                    </div>
                <hr>
                </div>
                
                <div class="WritingContent">
                    <div class="ArticleWritingTitle">
                        <div class="input-group mb-3">
                            <input id="title" type="text" class="form-control" placeholder="제목을 입력해 주세요." aria-label="Username" value="{{post.title}}">
                        </div>
                    </div>
                    <div class="ArticleContent">
                        <div id="article-description" class="form-floating">
                            <textarea id="description" class="form-control" placeholder="" maxlength={{maxlength}} >{{post.description}}</textarea>
                          </div>
                    </div>

                </div>
            </div><!--WritingWrap end-->
		</div><!-- middle container 끝-->

		

		<!--하단 탭바-->
		<nav id="bottom_tapbar" class="navbar fixed-bottom navbar-light bg-light" style="position:sticky; bottom:0; height:10%; max-height:10%; margin-top:1rem; padding:0;">
			<div class="container-fluid" style="padding:0;">
				<ins class="kakao_ad_area" style="display:none;" data-ad-unit    = "DAN-VgaPZkxM9B2j0lxu" data-ad-width   = "320" data-ad-height  = "100"></ins> 
				<script type="text/javascript" src="//t1.daumcdn.net/kas/static/ba.min.js" async></script>
</div>
			<div class="container-fluid">
				<div class="row">
					{% if pk %}
					<div class="col-3" id="bottom_home">
						<a href="{% url 'hzm:main_page' %}" >
							<span><i class="fa fa-home" id="bottom_home_btn" style="color:gray;"></i><span>
							<h2>홈</h2>
						</a>
					</div>
					<div class="col-3" id="bottom_club">
						<a href="{% url 'hzm:club' club.pk %}" >
							<span>
								<i class="fas fa-flag-checkered" id="bottom_club_btn" style="color:gray;" ></i>
							<span>
								<h2>클럽</h2>
						</a>
					</div>
					<div class="col-3" id="bottom_record">
						<a href="{% url 'hzm:personal_record' %}" >
							<span>
								<i class="fas fa-clipboard" id="bottom_club_btn" style="color:gray;" ></i>
							<span>
								<h2>개인기록</h2>
						</a>
					</div>
					<div class="col-3" id="bottom_user">
						<a href="{% url 'hzm:mypage' %}" >
							<span >
								<i class="fa fa-user" id="bottom_user_btn" style="color:gray;" ></i>
							</span>
							<h2>마이룸</h2>
						</a>
					</div>

					{% endif %}
				</div>
			</div>	
		</nav>
		<!--하단 탭바 끝-->



<!-- script start -->
	<script>
		function getTime() {
			var Now = new Date();
			var NowTime = Now.getFullYear();
			
			NowTime += '-' + String(Number(Now.getMonth()) +1) ;
			NowTime += '-' + Now.getDate();
			NowTime += ' ' + Now.getHours();
			NowTime += ':' + Now.getMinutes();
			NowTime += ':' + Now.getSeconds();
			return NowTime;
		}
				//경기신청모달 고가 평균 폼 확인
		function goga_form_check(data){
			data_=data.split(':')

			if(data.length != 8)
				return false;
			else if(data[2] != ':')
				return false;
			else if(data[5] != ':')
				return false;
			else if(isNaN(data_[0]))
				return false;
			else if(isNaN(data_[1]))
				return false;
			else if(isNaN(data_[2]))
				return false;

			return true;
		}
		//경기신청모달 경기 날짜 폼 체크
		function match_date_form_check(match_date) {
			if(match_date.length != 10) 
				return false;
			else if(match_date[4] != '-')
				return false;
			else if(match_date[7] != '-')
				return false;
			
			match_date_=match_date.split('-')

			if(isNaN(match_date_[0]))
				return false;
			else if(isNaN(match_date_[1]))
				return false;
			else if(isNaN(match_date_[2]))
				return false;

			return true;
		}
		//경기신청 모달 시간 체크
		function time_form_check(time){
			if(time.length != 5)
				return false;
			else if(time[2] != ':')
				return false;

			time_=time.split(':')
			if(isNaN(time_[0]))
				return false;
			else if (isNaN(time_[1]))
				return false;
			return true;
		}



		//모달에서 로그인 버튼 클릭
		$(document).on('click', '#modal_signin_btn', function(e) {
			var player_name = $('#modal_player_name').val();
			var player_passwd = $('#modal_player_passwd').val(); 

			console.log(player_name);
			console.log(player_passwd);
			$.ajax({
				url:"{% url 'hzm:ajax_signin' %}",
				type:'POST',
				data : {
					'player_name' : player_name,
					'player_passwd' : player_passwd,
					'csrfmiddlewaretoken' : "{{csrf_token}}",

				},
				success:function(msg) {
					console.log("login: "+msg);
					if( msg=="login_fail1") {
						return swal("존재하지 않는 아이디입니다");
					}
					else if (msg=="login_fail2") {
						return swal("잘못된 접근입니다.");
					}
					else if(msg=="login_fail3"){
						return swal("존재하지 않는 아이디입니다");
					}
					else if(msg=="auth_fail"){
						return swal("승인 대기중입니다 잠시만 기다려주세요!");
					}
					else {
						location.reload();
					}
				},
				error : function(error) {
					swal("아이디/비밀번호가 일치하지 않습니다.");
				}
			});
		});
		
		$(document).on('click','#logout_btn', function(e) {
			$.ajax({
				url:"{% url 'hzm:ajax_logout' %}",
				type:'GET',
				success:function(data) {
					swal("바이바이~");
					location.reload();
				},
				error : function(error) {
					swal("실패");
				}
			})
        });
        
        //글 수정 저장버튼
        $(document).on('click','#write_edit_btn', function() {
            var description =$('#description').val();
			var title=$('#title').val();
			var freeboard_pk="{{post.pk}}"

            if( $.trim(title)== '')return swal("제목을 입력해주세요");
            else if( $.trim(description)== '')return swal("제목을 입력해주세요");
           
            $.ajax({
                url: "{% url 'hzm:ajax_edit_freeboard_writing' %}",
                type:'POST',
                data : {
                    'csrfmiddlewaretoken' : "{{csrf_token}}",
                    'title':title,
					'description':description,
					'freeboard_pk':freeboard_pk,
                },success: function(data) {
					location.href="{% url 'hzm:freeboard_info' post.pk %}"

                },error : function(error) {
                    swal("저장실패")
                }
            })
		});
	</script>
	
</body>


<html>